In [43]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

# 데이터 불러오기
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv'
df = pd.read_csv(url)

df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
3            NaN     NaN  
4         3450.0  FEMALE  
..           ...     ...  
339          NaN     NaN  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[344 rows x 7 columns]

In [45]:
print(df['sex'].value_counts())

sex
MALE      168
FEMALE    165
Name: count, dtype: int64


In [47]:
#결측치 확인
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [49]:
label_encoders = {}
for column in df.columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

In [51]:
df

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0          0       2              42             56                  6   
1          0       2              45             43                 11   
2          0       2              51             49                 20   
3          0       2             164             80                 55   
4          0       2              22             62                 18   
..       ...     ...             ...            ...                ...   
339        2       0             164             80                 55   
340        2       0             105             12                 39   
341        2       0             136             26                 46   
342        2       0              89             17                 36   
343        2       0             131             30                 37   

     body_mass_g  sex  
0             31    1  
1             33    0  
2             12    0  
3             94    2  
4             19    0  
..           ...  ...  
339           94    2  
340           66    0  
341           87    1  
342           76    0  
343           80    1  

[344 rows x 7 columns]

In [53]:
#결측치 확인
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [55]:
print(df['sex'].value_counts())

sex
1    168
0    165
2     11
Name: count, dtype: int64


In [57]:
X = df.drop(['sex'], axis=1)  # 피처(입력값)
y = df['sex']  # 레이블(정답)

In [59]:
X

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0          0       2              42             56                  6   
1          0       2              45             43                 11   
2          0       2              51             49                 20   
3          0       2             164             80                 55   
4          0       2              22             62                 18   
..       ...     ...             ...            ...                ...   
339        2       0             164             80                 55   
340        2       0             105             12                 39   
341        2       0             136             26                 46   
342        2       0              89             17                 36   
343        2       0             131             30                 37   

     body_mass_g  
0             31  
1             33  
2             12  
3             94  
4             19  
..           ...  
339           94  
340           66  
341           87  
342           76  
343           80  

[344 rows x 6 columns]

In [61]:
y

0      1
1      0
2      0
3      2
4      0
      ..
339    2
340    0
341    1
342    0
343    1
Name: sex, Length: 344, dtype: int32

In [63]:
# standard scaler, X의 값을 평균0, 표춘편차1로 만들어줌. minmaxscaler : 0과1사이
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=0)

In [67]:
print(type(X_train))
print(type(X_test))
print(type(y_train))
print(type(y_test))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


In [69]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((275, 6), (69, 6), (275,), (69,))

In [71]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [73]:
clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.8695652173913043
[[30  3  0]
 [ 4 30  0]
 [ 2  0  0]]


In [75]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.855072463768116
[[29  4  0]
 [ 4 30  0]
 [ 2  0  0]]


In [77]:
clf_nn = MLPClassifier(random_state=0, max_iter=1000)
clf_nn.fit(X_train, y_train)

pred_nn = clf_nn.predict(X_test)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))


--- Neural Network Classifier ---
0.8840579710144928
[[29  4  0]
 [ 2 32  0]
 [ 2  0  0]]


In [79]:
# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.7971014492753623
[[27  2  4]
 [ 4 28  2]
 [ 2  0  0]]


In [81]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.8840579710144928
[[30  3  0]
 [ 3 31  0]
 [ 2  0  0]]
