In [6]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

df = pd.read_csv("/content/drive/MyDrive/car_evaluation.csv", header=None)

# 새로운 컬럼명 지정
df.columns = ['price', 'maint', 'doors', 'person', 'log_cap', 'safety', 'output']

df

price  maint  doors person log_cap safety output
0     vhigh  vhigh      2      2   small    low  unacc
1     vhigh  vhigh      2      2   small    med  unacc
2     vhigh  vhigh      2      2   small   high  unacc
3     vhigh  vhigh      2      2     med    low  unacc
4     vhigh  vhigh      2      2     med    med  unacc
...     ...    ...    ...    ...     ...    ...    ...
1723    low    low  5more   more     med    med   good
1724    low    low  5more   more     med   high  vgood
1725    low    low  5more   more     big    low  unacc
1726    low    low  5more   more     big    med   good
1727    low    low  5more   more     big   high  vgood

[1728 rows x 7 columns]

In [7]:
df.isnull().sum()

price      0
maint      0
doors      0
person     0
log_cap    0
safety     0
output     0
dtype: int64

In [25]:
label_encoders = {}
for column in df.columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

In [10]:
df

price  maint  doors  person  log_cap  safety  output
0         3      3      0       0        2       1       2
1         3      3      0       0        2       2       2
2         3      3      0       0        2       0       2
3         3      3      0       0        1       1       2
4         3      3      0       0        1       2       2
...     ...    ...    ...     ...      ...     ...     ...
1723      1      1      3       2        1       2       1
1724      1      1      3       2        1       0       3
1725      1      1      3       2        0       1       2
1726      1      1      3       2        0       2       1
1727      1      1      3       2        0       0       3

[1728 rows x 7 columns]

In [11]:
df['output'].value_counts()

output
2    1210
0     384
1      69
3      65
Name: count, dtype: int64

In [13]:
X = df.drop(['output'], axis=1)  # 피처(입력값)
y = df['output']  # 레이블(정답)

In [14]:
X

price  maint  doors  person  log_cap  safety
0         3      3      0       0        2       1
1         3      3      0       0        2       2
2         3      3      0       0        2       0
3         3      3      0       0        1       1
4         3      3      0       0        1       2
...     ...    ...    ...     ...      ...     ...
1723      1      1      3       2        1       2
1724      1      1      3       2        1       0
1725      1      1      3       2        0       1
1726      1      1      3       2        0       2
1727      1      1      3       2        0       0

[1728 rows x 6 columns]

In [15]:
y

0       2
1       2
2       2
3       2
4       2
       ..
1723    1
1724    3
1725    2
1726    1
1727    3
Name: output, Length: 1728, dtype: int64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [17]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1382, 6), (346, 6), (1382,), (346,))

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [27]:
clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.9277456647398844
[[ 67   1   8   1]
 [ 10   4   0   0]
 [  2   0 240   0]
 [  3   0   0  10]]


In [20]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.6907514450867052
[[  6   0  63   8]
 [  1   0  13   0]
 [ 11   0 231   0]
 [  3   0   8   2]]


In [26]:
clf_nn = MLPClassifier(random_state=0, max_iter=1000)
clf_nn.fit(X_train, y_train)

pred_nn = clf_nn.predict(X_test)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))


--- Neural Network Classifier ---
0.9739884393063584
[[ 75   0   2   0]
 [  1  13   0   0]
 [  3   2 237   0]
 [  1   0   0  12]]


In [22]:
# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.9797687861271677
[[ 75   1   1   0]
 [  0  14   0   0]
 [  3   0 239   0]
 [  2   0   0  11]]


In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.9855491329479769
[[ 76   0   1   0]
 [  1  13   0   0]
 [  1   0 241   0]
 [  1   1   0  11]]
